# Mudar a porta padrao do servidor para evitar conflitos
server.port=8081

spring.application.name=loginsystem


# Ativar a consola web do H2 para podermos inspecionar a BD no browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração da ligacao à base de dados em memoria
spring.datasource.url=jdbc:h2:mem:logindb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar no terminal as queries SQL que o Spring faz por baixo dos panos
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update